name: build

on:
  workflow_dispatch: 
    
env:
  SOLUTION_FILE_PATH: .\build\bcm2836\buildbcm2836.sln

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        BUILD_CONFIGURATION: [Release, Debug]
        PLATFORM: [ARM, ARM64]
    steps:
    - uses: actions/checkout@v4.2.2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.BUILD_CONFIGURATION}} /p:Platform=${{matrix.PLATFORM}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload
      uses: actions/upload-artifact@v4.6.0
      with:
         name: windows-drivers_${{matrix.PLATFORM}}_${{matrix.BUILD_CONFIGURATION}}
         path: ${{env.GITHUB_WORKSPACE}}
